/// <reference types="node" />

/// The #10044 transplant thesis test (and its HONEST LIMIT finding).
///
/// #10044 is a rolldown 1.1.3 LINK failure: `[MISSING_EXPORT] "RESET" is not exported by
/// "@griffel/core/src/index.js"`, where `@griffel/react` does `export { RESET, … } from '@griffel/core'`
/// but `@griffel/core` exposes `RESET` only transitively via `export * from './constants.js'`. It
/// reproduces on the REAL `@fluentui/react-text` (+@griffel) graph (bare rolldown 1.1.3 on
/// `import { Title1 } from '@fluentui/react-text'`), and is fixed in 1.1.4. Five hand-written synthetics
/// (a minimal chain, package-boundary + `sideEffects:false`, a same-statement multi-name re-export
/// mirror, and the direct real @griffel graph) all FAILED to trigger it even on 1.1.3 — the prior
/// investigation concluded the trigger is an EMERGENT property of the real graph's module scale + link
/// order, not an isolable structural motif.
///
/// This script builds a FAITHFUL transplant of the extracted @griffel/@fluentui graph — the full
/// topology (2122 modules), the exact `RESET`-only-via-star re-export chain, a retained `RESET` read,
/// and the package boundaries — validates that the RENDERED model contains the exact `export { RESET }
/// from …` + `export *` shape, and runs it against rolldown 1.1.3 and 1.1.4.
///
/// RESULT (recorded in `.agents/evidence/transplant-10044-limit.json`): the transplant does NOT
/// reproduce — it is GREEN on 1.1.3 at every scope, WITH the exact structural chain present in its
/// rendered output. So the honest finding is a precise LIMIT of the technique: the transplant carries
/// every REPRESENTABLE ingredient (the star->named RESET chain, full module scale, package boundaries,
/// `sideEffects:false` where the metadata-purity contract allows) but NOT the emergent LINK ORDER the
/// bug depends on — an order that emerges from the real modules' bodies and rolldown's own scheduling of
/// them, which the anonymized side-effect/re-export skeleton (no real bodies; each re-export name a
/// SEPARATE statement; module order fixed by synthetic ids) does not reconstruct.
///
///   node scripts/transplant/repro-10044.ts <griffel-graph.json>
///
/// The griffel graph is regenerated by building `import { Title1 } from '@fluentui/react-text'` (or the
/// repro app) with the skeleton extractor on a WORKING rolldown (>=1.1.4) — see the doc. Targets are the
/// redset npm cache (`/tmp/order-fuzzer-regression-targets/{1.1.3,1.1.4}`).

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { analyzeProgram } from "../../src/analyzed-program.ts";
import {
  normalizeLegacyReads,
  type EntryModel,
  type EsmDependencyOperation,
  type ModuleModel,
  type PackageModel,
  type ProgramModel,
  type ScheduleOperation,
} from "../../src/model.ts";
import { executeProgram } from "../../src/program-run.ts";
import { renderProgram } from "../../src/render.ts";
import { validateProgramModel } from "../../src/validate-model.ts";
import { loadGraph, type GraphModule, type SkeletonGraph } from "./graph.ts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const EVIDENCE_OUT =
  process.env.EVIDENCE_OUT ?? resolve(REPO_ROOT, ".agents/evidence/transplant-10044-limit.json");
const TARGET_CACHE = process.env.REDSET_TARGET_CACHE ?? "/tmp/order-fuzzer-regression-targets";
const RESET = "RESET";

interface BuildConfig {
  readonly scope: "griffel" | "full";
  readonly retainReset: boolean;
  readonly packages: boolean;
}

interface Chain {
  readonly constantsId: string;
  readonly coreIndexId: string;
  readonly reactIndexId: string;
}

function locateChain(graph: SkeletonGraph): Chain {
  const constantsId = graph.modules.find((m) => m.id.includes("@griffel/core/src/constants"))?.id;
  const coreIndexId = graph.modules.find((m) => m.id.endsWith("@griffel/core/src/index.js"))?.id;
  const reactIndexId = graph.modules.find((m) => m.id.endsWith("@griffel/react/src/index.js"))?.id;
  if (!constantsId || !coreIndexId || !reactIndexId) {
    throw new Error("graph does not contain the @griffel RESET chain (constants/core/react index)");
  }
  return { constantsId, coreIndexId, reactIndexId };
}

/// Build a faithful transplant preserving the re-export SHAPE (star/named/namespace) + topology, with a
/// retained RESET read routed through react/index's re-export.
function buildFaithful(graph: SkeletonGraph, chain: Chain, config: BuildConfig): ProgramModel {
  const byId = new Map(graph.modules.map((m) => [m.id, m]));
  let keptIds: string[];
  if (config.scope === "griffel") {
    const kept = new Set<string>();
    const queue = [chain.reactIndexId];
    while (queue.length > 0) {
      const id = queue.shift()!;
      if (kept.has(id) || !byId.has(id) || !id.includes("@griffel")) continue;
      kept.add(id);
      for (const target of byId.get(id)!.importedIds) queue.push(target);
    }
    kept.add(chain.constantsId).add(chain.coreIndexId);
    keptIds = [...kept];
  } else {
    keptIds = graph.modules.map((m) => m.id);
  }
  const keptSet = new Set(keptIds);
  keptIds.sort();
  const indexOf = new Map(keptIds.map((id, index) => [id, index]));
  const mid = (id: string): string => `m${indexOf.get(id)}`;

  const modules: ModuleModel[] = keptIds.map((id) => {
    const src = byId.get(id)!;
    const dependencies: EsmDependencyOperation[] = [];
    const reexportTargets = new Set<string>();
    for (const target of src.starReexportTargets) {
      if (!keptSet.has(target)) continue;
      dependencies.push({ kind: "esm-reexport-star", target: mid(target) });
      reexportTargets.add(target);
    }
    for (const reexport of src.namedReexports) {
      if (!keptSet.has(reexport.target)) continue;
      reexportTargets.add(reexport.target);
      for (const exported of Object.values(reexport.names)) {
        dependencies.push({
          kind: "esm-reexport-named",
          target: mid(reexport.target),
          sourceName: exported,
          exportedName: exported,
        });
      }
    }
    for (const reexport of src.nsReexports) {
      if (!keptSet.has(reexport.target)) continue;
      dependencies.push({
        kind: "esm-reexport-namespace",
        target: mid(reexport.target),
        exportedName: `ns_${mid(reexport.target)}`,
      });
      reexportTargets.add(reexport.target);
    }
    const seen = new Set<string>();
    for (const target of src.importedIds) {
      if (!keptSet.has(target) || reexportTargets.has(target) || seen.has(target)) continue;
      seen.add(target);
      dependencies.push({ kind: "esm-side-effect-import", target: mid(target) });
    }
    const model: ModuleModel = { id: mid(id), format: "esm", dependencies, events: [] };
    if (id === chain.constantsId) {
      const localExports = src.localExports.length > 0 ? src.localExports : [RESET];
      return { ...model, localExports } as ModuleModel;
    }
    return model;
  });

  const entryModules: ModuleModel[] = [];
  const entries: EntryModel[] = [];
  const schedule: ScheduleOperation[] = [];
  if (config.retainReset) {
    const rid = `m${keptIds.length}`;
    entryModules.push({
      id: rid,
      format: "esm",
      dependencies: [
        {
          kind: "esm-value-import",
          target: mid(chain.reactIndexId),
          importedName: RESET,
          localName: "reset",
        },
      ],
      events: [{ module: rid, phase: "evaluate", value: 1, reads: [{ binding: "reset" }] }],
    });
    entries.push({ name: "eReset", moduleId: rid });
    schedule.push({ kind: "import-entry", entry: "eReset" });
  }
  const rootId = `m${keptIds.length + 1}`;
  entryModules.push({
    id: rootId,
    format: "esm",
    dependencies: [{ kind: "esm-side-effect-import", target: mid(chain.reactIndexId) }],
    events: [{ module: rootId, phase: "evaluate", value: 2 }],
  });
  entries.push({ name: "eRoot", moduleId: rootId });
  schedule.push({ kind: "import-entry", entry: "eRoot" });

  let packages: PackageModel[] | undefined;
  if (config.packages) {
    const byPackage = new Map<string, GraphModule[]>();
    for (const id of keptIds) {
      const pkg = byId.get(id)!.pkg;
      if (!pkg) continue;
      const list = byPackage.get(pkg.name) ?? [];
      list.push(byId.get(id)!);
      byPackage.set(pkg.name, list);
    }
    const emittedById = new Map(modules.map((m) => [m.id, m]));
    const eligible = (id: string): boolean => {
      const m = emittedById.get(mid(id));
      return (
        m !== undefined &&
        m.events.length === 0 &&
        !m.dependencies.some((d) => d.kind === "esm-side-effect-import")
      );
    };
    packages = [...byPackage].map(([, members], index) => {
      const sideEffects =
        members[0]!.pkgSideEffects === false && members.every((m) => eligible(m.id)) ? false : true;
      return { name: `pkg${index}`, sideEffects, moduleIds: members.map((m) => mid(m.id)) };
    });
  }

  return normalizeLegacyReads({
    modules: [...modules, ...entryModules],
    entries,
    schedule,
    ...(packages ? { packages } : {}),
  } as ProgramModel);
}

/// Confirm the RENDERED model carries the exact bug shape: a file re-exporting RESET by name from a file
/// that only obtains RESET via `export *`.
function renderedChainPresent(program: ProgramModel): {
  readonly resetReexporters: number;
  readonly starFiles: number;
} {
  const rendered = renderProgram(analyzeProgram(program));
  let resetReexporters = 0;
  let starFiles = 0;
  for (const file of rendered.files) {
    const contents = file.contents.toString();
    if (/export \{ RESET \} from|export \{ RESET as/.test(contents)) resetReexporters += 1;
    if (/export \* from/.test(contents)) starFiles += 1;
  }
  return { resetReexporters, starFiles };
}

async function runOn(program: ProgramModel, distPath: string): Promise<string> {
  const run = await executeProgram(program, { rolldownPackage: distPath, onDemandWrapping: true });
  return run.verdict.kind === "pass" ? "pass" : run.verdict.signature;
}

function gitOutput(args: readonly string[]): string {
  try {
    return execFileSync("git", args, { cwd: REPO_ROOT, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

async function main(): Promise<number> {
  const graphPath = process.argv[2];
  if (!graphPath || !existsSync(graphPath)) {
    process.stderr.write(
      `usage: repro-10044.ts <griffel-graph.json>\n  (regenerate the graph with the extractor — see .agents/docs/transplant-cell.md)\n`,
    );
    return 2;
  }
  const dist113 = resolve(TARGET_CACHE, "1.1.3/node_modules/rolldown/dist/index.mjs");
  const dist114 = resolve(TARGET_CACHE, "1.1.4/node_modules/rolldown/dist/index.mjs");
  for (const [version, dist] of [
    ["1.1.3", dist113],
    ["1.1.4", dist114],
  ] as const) {
    if (!existsSync(dist)) {
      process.stderr.write(
        `FAIL: rolldown ${version} target missing: ${dist} (run npm run regression:redset once to cache it)\n`,
      );
      return 2;
    }
  }

  const graph = loadGraph(graphPath);
  const chain = locateChain(graph);
  process.stderr.write(`#10044 transplant test — graph ${graph.modules.length} modules\n`);

  const configs: BuildConfig[] = [
    { scope: "griffel", retainReset: true, packages: false },
    { scope: "full", retainReset: true, packages: false },
    { scope: "full", retainReset: true, packages: true },
    { scope: "full", retainReset: false, packages: true },
  ];
  const matrix = [];
  let anyReproduced = false;
  for (const config of configs) {
    const program = buildFaithful(graph, chain, config);
    const errors = validateProgramModel(analyzeProgram(program));
    if (errors.length > 0) {
      matrix.push({ config, valid: false, errors: errors.slice(0, 4) });
      continue;
    }
    const chainShape = renderedChainPresent(program);
    const on113 = await runOn(program, dist113);
    const on114 = await runOn(program, dist114);
    const reproduced = on113.includes("MISSING_EXPORT") || on113.includes("link");
    if (reproduced) anyReproduced = true;
    matrix.push({
      config,
      valid: true,
      modules: program.modules.length,
      renderedChain: chainShape,
      on113,
      on114,
      reproduced,
    });
    process.stdout.write(
      `${config.scope} retainReset=${config.retainReset} pkg=${config.packages}: ` +
        `chain(reset-reexporters=${chainShape.resetReexporters},star-files=${chainShape.starFiles}) ` +
        `1.1.3=${on113 === "pass" ? "GREEN" : on113.slice(0, 40)} 1.1.4=${on114 === "pass" ? "GREEN" : "RED"}\n`,
    );
  }

  const finding = anyReproduced
    ? "TRANSPLANT REPRODUCED #10044 — register RED-10044 bracket"
    : "HONEST LIMIT: the faithful transplant carries the exact star->named RESET chain at full scale (verified in the rendered output) yet is GREEN on rolldown 1.1.3 — the emergent link order the bug depends on is not reconstructed by the anonymized side-effect/re-export skeleton";
  const evidence = {
    proof: "#10044 real-graph link-failure transplant test",
    generatedAt: new Date().toISOString(),
    head: gitOutput(["rev-parse", "HEAD"]),
    node: process.version,
    graphPath,
    graphModules: graph.modules.length,
    realGraphReproduces:
      "confirmed out-of-band: bare rolldown 1.1.3 on `import { Title1 } from '@fluentui/react-text'` throws [MISSING_EXPORT] \"RESET\"; 1.1.4 builds",
    anyReproduced,
    finding,
    matrix,
  };
  mkdirSync(dirname(EVIDENCE_OUT), { recursive: true });
  writeFileSync(EVIDENCE_OUT, `${JSON.stringify(evidence, null, 2)}\n`);
  process.stderr.write(`\nwrote evidence to ${EVIDENCE_OUT}\n`);
  process.stdout.write(`\n${finding}\n`);
  return 0;
}

const invokedPath = process.argv[1];
if (invokedPath !== undefined && import.meta.url === pathToFileURL(resolve(invokedPath)).href) {
  process.exit(await main());
}
